### PR TITLE
Fragmentization

### PR DESCRIPTION
**Pull request by Lozu**
Conversion of Login/Register Activities to respective Fragments

Assignment [Dec 8]: Switch Login and Register activities into fragments + PR

### CODE REVIEW

**Comment by akoteykula** [comment]
I’ve reviewed the pull request, and here are my observations:

1. **Password visibility:** The password is not hidden when typing. Please ensure that the input field masks the password appropriately for better user experience and security.

2. **Password field behavior:** The password field expands when a newline character is entered. It would be better to restrict the input to prevent users from adding newline characters (`\n`).

Screenshot 2024-12-09 at 10 13 00

On the positive side:
- Login functionality works as expected.
- Registration functionality works as expected and updates the Login screen as intended.

Overall, good work. Let me know if you need any assistance.

**Review by akoteykula — COMMENTED** [review]
I’ve reviewed the pull request, and here are my observations:

1. **Password visibility:** The password is not hidden when typing. Please ensure that the input field masks the password appropriately for better user experience and security.

2. **Password field behavior:** The password field expands when a newline character is entered. It would be better to restrict the input to prevent users from adding newline characters (`\n`).

Screenshot 2024-12-09 at 10 13 00

On the positive side:
- Login functionality works as expected.
- Registration functionality works as expected and updates the Login screen as intended.

Overall, good work. Let me know if you need any assistance.

**Comment by Lozu** [comment]
@akoteykula, problem is solved in the latest commit. Please check

**Comment by akoteykula** [comment]
Approve. Everything works.

**Pull request merged**
